-- Script generated by SimpleSpy - credits to exx#9394
wait()
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

game:GetService("ReplicatedStorage").RE:FireServer(unpack(args))
local args = {
    [1] = "BuyItem",
    [2] = "Cookie"
}

